#!/bin/bash

# script to add ssh keys into ssh-agent

if [ ! -f /tmp/ssh-agent.sh ]
then
	ssh-agent > /tmp/ssh-agent.sh
	source /tmp/ssh-agent.sh > /dev/null
	ssh-add ~/.ssh/*.osk
	ssh-add ~/.ssh/*.psk
fi
