#!/bin/bash

if [ "$1" = "on" ]; then
    # turn on tv output
    xrandr --output HDMI-0 --auto --left-of DP-0
    # set HDMI4 as default audio output
    pacmd set-default-sink "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3"
else
    # set DAC as default audio output
    pacmd set-default-sink "alsa_output.usb-Burr-Brown_from_TI_USB_Audio_DAC-00.analog-stereo"
    # disable tv output
    xrandr --output HDMI-0 --off
fi

~/.config/.fehbg
killall polybar; polybar ophelia &
bspc wm -O DP-4 DP-0 DP-2 HDMI-0
