#! /bin/bash

sxhkd &

xsetroot -cursor_name left_ptr

# Monitor setup on fancy new laptop
if [ $(hostname) = miranda ]; then
	xrandr --output eDP1 --auto --primary
fi

# Monitor setup for desktop
if [ $(hostname) = ophelia ]; then
	xrandr --output HDMI-0 --off
    ~/.screenlayout/triple-one-vertical.sh
	#xrandr --output DP-4 --auto --primary
    #xrandr --output DP-2 --auto --right-of DP-4 --rotate right
	#xrandr --output DP-0 --auto --left-of DP-4
fi

# For fixing touchpad scroll direction
if [ $(hostname) = miranda ]; then
	synclient VertScrollDelta=-250
	synclient HorizScrollDelta=-250
	synclient TapButton1=1
	synclient TapButton2=3
	synclient TapButton3=2
	synclient PalmDetect=1
fi

if [ $(hostname) = miranda ]
then
	bspc monitor eDP1 -d web work code push chat play read misc
	polybar miranda &
fi

if [ $(hostname) = ophelia ]
then
	bspc wm -O DP-4 DP-0 DP-2
	bspc monitor DP-4 -d web work code push chat play read misc
	bspc monitor DP-0 -d left
	bspc monitor DP-2 -d right
	bspc monitor HDMI-0 --remove
	polybar ophelia &
	polybar ophelia-left &
    polybar ophelia-right &
fi

# Set the wallpaper
eval $(cat ~/.config/.fehbg)

bspc config bottom_padding			40
bspc config top_padding				20
bspc config right_padding			20
bspc config left_padding			20
bspc config window_gap				5
bspc config border_width			1
bspc config normal_border_color		\#706B82
bspc config active_border_color		\#706B82
bspc config focused_border_color	\#976870
bspc config presel_feedback_color	\#707880
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		false

bspc rule -a scratchpad sticky=on state=floating
bspc rule -a Onboard sticky=on state=floating border=off
bspc rule -a Keybase state=floating
bspc rule -a KeeWeb state=floating
bspc rule -a feh state=floating

picom &
redshift-gtk &
dropbox
# run_keybase &
# telegram-desktop &
