#! /bin/bash

sxhkd &

bspc monitor ^1 -n '' -d 1 2 3 4

if [ `cat /etc/hostname` == "tuesday" ]
then
	bspc monitor ^2 -n '' -d 5 6 7 8
	bspc monitor ^3 -n '' -d 9 0
fi

bspc config border_width 0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true

compton &
theme sedated
