#! /bin/bash

sxhkd &

xsetroot -cursor_name left_ptr

# Monitor setup on fancy new laptop
if [ $(hostname) = miranda ]; then
	xrandr --output eDP1 --auto --primary
fi

# Monitor setup for desktop
if [ $(hostname) = ophelia ]; then
	xrandr --output HDMI-0 --off
    ~/.screenlayout/triple-two-vertical.sh
fi

# For fixing touchpad scroll direction
if [ $(hostname) = miranda ]; then
	synclient VertScrollDelta=-250
	synclient HorizScrollDelta=-250
	synclient TapButton1=1
	synclient TapButton2=3
	synclient TapButton3=2
	synclient PalmDetect=1
fi

bspc config bottom_padding 5

if [ $(hostname) = miranda ]
then
	# bspc monitor eDP1 -d web work code push chat mail play misc
	bspc monitor eDP1 -d        
    bspc config -m eDP1 bottom_padding 5
    bspc config -m eDP1 top_padding 30
    eww/target/release/eww daemon
    eww/target/release/eww open bar_left
    eww/target/release/eww open bar_right
	# polybar miranda &
fi

if [ $(hostname) = ophelia ]
then
	bspc wm -O DP-4 DP-0 DP-2
	bspc monitor DP-4 -d web work code push chat play read misc
	bspc monitor DP-0 -d left
	bspc monitor DP-2 -d right
	bspc monitor HDMI-0 --remove
    bspc config -m DP-4 bottom_padding 25
	polybar ophelia &
fi

# Set the wallpaper
#eval $(cat ~/.config/.fehbg)
wal -i ~/.wallpaper

bspc config top_padding				5
bspc config right_padding			5
bspc config left_padding			5
bspc config window_gap				5
bspc config border_width			1
bspc config normal_border_color		\#555555
bspc config active_border_color		\#555555
bspc config focused_border_color	\#BBBBBB
bspc config presel_feedback_color	\#707880
bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		false

bspc rule -a scratchpad sticky=on state=floating
bspc rule -a Onboard sticky=on state=floating border=off
bspc rule -a Keybase state=floating
bspc rule -a KeeWeb state=floating
bspc rule -a feh state=floating

picom &
redshift-gtk &
dropbox
# run_keybase &
# telegram-desktop &
