alias upgrade="sudo pacman -Syu"
alias ls="exa"
alias ll="exa -l"
alias la="exa -la"
alias status="git status"
alias add="git add -A"
alias com="git commit"
alias push="git push"
alias pull="git pull"
alias search="ps -ef | grep -i"
alias x="startx"
alias grep="grep --color=auto"
alias mc="mc -b"
alias ezmount="sudo mount -t auto -o 'users,uid=1000,gid=1000,fmask=0113,dmask=0002'"
alias syncipod="rsync -rvc ~/media/music/ /mnt/ipod/music"
alias android-studio="_JAVA_AWT_WM_NONREPARENTING=1 android-studio"
alias stream-resize-todo="xdotool selectwindow windowsize 640 434"
alias stream-window-snap-left-half="xdotool selectwindow windowsize 816 918 windowmove 3285 826"
alias stream-window-snap-right-half="xdotool selectwindow windowsize 816 918 windowmove 4137 826"
alias stream-window-snap-full="xdotool selectwindow windowsize 1632 918 windowmove 3285 826"
