alias upgrade="sudo apt-get update && sudo apt-get upgrade -y"
alias ls="ls --color"
alias ll="ls -lh --color"
alias la="ls -lah --color"
alias tty-clock="tty-clock -SscC4"
alias addkeys="~/.scripts/addkeys.sh"
alias status="git status"
alias add="git add -A"
alias com="git commit"
alias push="git push"
alias pull="git pull"
alias search="ps -ef | grep -i"
alias x="startx"
alias grep="grep --color=auto"
alias night="redshift -O 3700"
alias day="redshift -O 6500"
