#! /bin/sh

sxhkd &

HOSTNAME = $(hostname)

if [ "$(hostname)" == "friday" ]
then
	bspc monitor LVDS1 -d 1 2 3 4
elif [ "$(hostname)" == "tuesday" ]
then
	bspc monitor DP-2 -n A -d 1 2 3 4
	bspc monitor DP-4 -n B -d 5 6 7 8
else
	echo "Unrecognized hostname"
fi

bspc config border_width	1
bspc config top_padding		20
bspc config window_gap		5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

compton --config "/home/kienan/.config/compton.conf" -b

panel &
