#! /bin/bash

sxhkd &

bspc monitor ^1 -n '' -d 1 2 3 4

if [ `hostname` == "tuesday" ]
then
	bspc monitor ^2 -n '' -d 5 6 7 8
fi

bspc config top_padding 0
bspc config -m ^1 top_padding 25
bspc config border_width 1
bspc config window_gap 15
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true

compton --config "/home/kienan/.config/compton.conf" -b

panel &
# Custom panel setup
# launch_panel.sh &

redshift -l 42:73 &
